version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
  apiproxy:
    restart: always
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    environment:
      - REDSKY_ADDRESS
      - REDSKY_OAUTH2_CLIENT_ID
      - REDSKY_OAUTH2_CLIENT_SECRET
      - DOCKER_ENV=1
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
